/**
 * Route Exposure Configuration
 * ============================
 *
 * Loads computed route exposure data from route_exposure.json.
 * This data is generated by scripts/compute_route_exposure.py using
 * coastline geometry analysis (fetch distance to land).
 *
 * The exposure scores are physics-based, not hand-authored, ensuring
 * truthful comparisons between routes (e.g., Hyannis-Nantucket correctly
 * shows higher exposure than Woods Hole-Vineyard Haven).
 */

import routeExposureData from './route_exposure.json';

// 16-point compass directions
export const COMPASS_DIRECTIONS = [
  'N', 'NNE', 'NE', 'ENE',
  'E', 'ESE', 'SE', 'SSE',
  'S', 'SSW', 'SW', 'WSW',
  'W', 'WNW', 'NW', 'NNW',
] as const;

export type CompassDirection = typeof COMPASS_DIRECTIONS[number];

export interface RouteExposure {
  route_id: string;
  origin_port: string;
  destination_port: string;
  exposure_by_dir: Record<CompassDirection, number>;
  fetch_km_by_dir: Record<CompassDirection, number>;
  avg_exposure: number;
  top_exposure_dirs: CompassDirection[];
}

interface RouteExposureFile {
  version: string;
  computed_at: string;
  parameters: {
    sample_points: number;
    max_fetch_km: number;
    ray_step_m: number;
    note?: string;
  };
  routes: Record<string, RouteExposure>;
}

const exposureFile = routeExposureData as RouteExposureFile;

/**
 * Get exposure data for a specific route
 */
export function getRouteExposure(routeId: string): RouteExposure | null {
  return exposureFile.routes[routeId] || null;
}

/**
 * Get all routes with exposure data
 */
export function getAllRouteExposures(): Record<string, RouteExposure> {
  return exposureFile.routes;
}

/**
 * Get exposure metadata (version, computation time, etc.)
 */
export function getExposureMetadata(): {
  version: string;
  computed_at: string;
  parameters: RouteExposureFile['parameters'];
} {
  return {
    version: exposureFile.version,
    computed_at: exposureFile.computed_at,
    parameters: exposureFile.parameters,
  };
}

/**
 * Convert wind direction in degrees to nearest compass bucket
 *
 * @param degrees - Wind direction in degrees (0-360)
 * @returns Nearest compass direction
 */
export function degreesToCompassBucket(degrees: number): CompassDirection {
  // Normalize to 0-360
  const normalized = ((degrees % 360) + 360) % 360;

  // Each compass point spans 22.5 degrees (360 / 16)
  const index = Math.round(normalized / 22.5) % 16;

  return COMPASS_DIRECTIONS[index];
}

/**
 * Get exposure score for a route given a wind direction
 *
 * @param routeId - Route identifier (e.g., 'wh-vh-ssa')
 * @param windFromDegrees - Wind direction in degrees (where wind is coming FROM)
 * @returns Exposure score 0..1, or null if route not found
 */
export function getExposureForDirection(
  routeId: string,
  windFromDegrees: number
): number | null {
  const exposure = getRouteExposure(routeId);
  if (!exposure) return null;

  const compassDir = degreesToCompassBucket(windFromDegrees);
  return exposure.exposure_by_dir[compassDir] ?? null;
}

/**
 * Calculate route exposure modifier for scoring
 *
 * This converts the 0..1 exposure score into a bounded modifier
 * that can be applied to the risk score.
 *
 * Bounds: [-10, +15] points
 * - Low exposure (< 0.4): Reduces score (more sheltered)
 * - Medium exposure (0.4-0.6): No change
 * - High exposure (> 0.6): Increases score (more exposed)
 *
 * @param routeId - Route identifier
 * @param windFromDegrees - Wind direction in degrees
 * @returns Modifier in range [-10, +15], or 0 if route not found
 */
export function calculateExposureModifier(
  routeId: string,
  windFromDegrees: number
): number {
  const exposure = getExposureForDirection(routeId, windFromDegrees);

  if (exposure === null) {
    return 0; // No data, no modification
  }

  // Map exposure 0..1 to modifier -10..+15
  // Center point at 0.5 exposure = 0 modifier
  // exposure < 0.5 = negative modifier (sheltered)
  // exposure > 0.5 = positive modifier (exposed)

  if (exposure < 0.4) {
    // Sheltered: reduce score by up to 10 points
    // 0.0 exposure = -10, 0.4 exposure = 0
    return Math.round(-10 * (1 - exposure / 0.4));
  } else if (exposure > 0.6) {
    // Exposed: increase score by up to 15 points
    // 0.6 exposure = 0, 1.0 exposure = +15
    return Math.round(15 * (exposure - 0.6) / 0.4);
  }

  // Medium exposure: no change
  return 0;
}

/**
 * Get formatted top exposure directions for display
 *
 * @param routeId - Route identifier
 * @returns Array of top 3 directions, or null if route not found
 */
export function getTopExposureDirections(routeId: string): CompassDirection[] | null {
  const exposure = getRouteExposure(routeId);
  if (!exposure) return null;

  return exposure.top_exposure_dirs as CompassDirection[];
}

/**
 * Format a direction with "winds" suffix for display
 *
 * @param direction - Compass direction
 * @returns Formatted string like "SW winds"
 */
export function formatDirectionLabel(direction: CompassDirection): string {
  return `${direction} winds`;
}
